// Artworks
export const FETCH_ARTWORKS = "FETCH_ARTWORKS";
export const UNIQUE_ARTWORK_CATEGORIES = "UNIQUE_ARTWORK_CATEGORIES";
export const UNIQUE_ARTWORK_LOCATIONS = "UNIQUE_ARTWORK_LOCATIONS";
export const FILTERED_ARTWORKS = "FILTERED_ARTWORKS";
export const ARTWORK_SPOTLIGHTS = "ARTWORK_SPOTLIGHTS";
export const ARTWORK_HERO = "ARTWORK_HERO";
export const INCLUDE_ARTWORK_BY_CATEGORY = "INCLUDE_ARTWORK_BY_CATEGORY";
export const INCLUDE_ARTWORK_BY_LOCATION = "INCLUDE_ARTWORK_BY_LOCATION";
export const INCLUDE_ARTWORK_BY_TAG = "INCLUDE_ARTWORK_BY_TAG";
export const SORT_ARTWORKS_BY_DATE = "SORT_ARTWORKS_BY_DATE";
// Texts
export const FETCH_TEXTS = "FETCH_TEXTS";
export const UNIQUE_TEXT_CATEGORIES = "UNIQUE_TEXT_CATEGORIES";
export const INCLUDE_TEXT_BY_CATEGORY = "INCLUDE_TEXT_BY_CATEGORY";
export const FILTERED_TEXTS = "FILTERED_TEXTS";
