// Artworks
export const FETCH_ARTWORKS = "FETCH_ARTWORKS";
export const UNIQUE_ARTWORK_CATEGORIES = "UNIQUE_ARTWORK_CATEGORIES";
export const UNIQUE_ARTWORK_LOCATIONS = "UNIQUE_ARTWORK_LOCATIONS";
export const FILTERED_ARTWORKS = "FILTERED_ARTWORKS";
export const ARTWORK_SPOTLIGHTS = "ARTWORK_SPOTLIGHTS";
export const ARTWORK_HERO = "ARTWORK_HERO";
export const INCLUDE_ARTWORK_BY_CATEGORY = "INCLUDE_ARTWORK_BY_CATEGORY";
export const INCLUDE_ARTWORK_BY_LOCATION = "INCLUDE_ARTWORK_BY_LOCATION";
export const INCLUDE_ARTWORK_BY_TAG = "INCLUDE_ARTWORK_BY_TAG";
export const SORT_ARTWORKS_BY_DATE = "SORT_ARTWORKS_BY_DATE";

// import {
// 	FETCH_ARTWORKS,
// 	UNIQUE_ARTWORK_CATEGORIES,
// 	UNIQUE_ARTWORK_LOCATIONS,
// 	FILTERED_ARTWORKS,
// 	ARTWORK_SPOTLIGHTS,
// 	ARTWORK_HERO,
// 	INCLUDE_ARTWORK_BY_CATEGORY,
// 	INCLUDE_ARTWORK_BY_LOCATION,
// 	INCLUDE_ARTWORK_BY_TAG,
// 	// SORT_ARTWORKS_BY_DATE,
// } from "@/stores/constants";
// Users
export const ADD_SELECTED_ARTWORK_CATEGORIES =
	"ADD_SELECTED_ARTWORK_CATEGORIES";
export const ADD_SELECTED_ARTWORK_LOCATIONS = "ADD_SELECTED_ARTWORK_LOCATIONS";
export const ADD_SELECTED_TEXT_CATEGORIES = "ADD_SELECTED_TEXT_CATEGORIES";
export const CLEAR_USER_ARTWORK_FILTER_SELECTIONS =
	"CLEAR_USER_ARTWORK_FILTER_SELECTIONS";
// Texts
export const FETCH_TEXTS = "FETCH_TEXTS";
export const UNIQUE_TEXT_CATEGORIES = "UNIQUE_TEXT_CATEGORIES";
export const INCLUDE_TEXT_BY_CATEGORY = "INCLUDE_TEXT_BY_CATEGORY";
export const FILTERED_TEXTS = "FILTERED_TEXTS";
